import { Inter } from 'next/font/google'
import './globals.css'

// Noto Sans JPをインポート
import { Noto_Sans_JP } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// Noto Sans JPのフォント設定
const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata = {
  title: 'Create.xyz App',
  description: 'Generated by create.xyz',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${notoSansJP.className}`}>{children}</body>
    </html>
  )
}